---

frecuencias:
  - "_u"
  - "_p _u -"
  - "_p _u + 2 /"
  - "_u _t * 22000 %"
  - "_p _u _p * * 1000 %"
  - "_p _p _p * + sin _u _u * * abs"
  - "_t _u 1 + / _t _u 1 + * + _t 6 >> * 44100 %"
  - "_p"
